#===========================================================================================
# Alumno: Ibai Castañon Osorio
# Email: icasto01@estudiantes.unileon.es
#
# Descripcion: Fichero de configuracion de docker-compose para organizar la infraestructura
# de contenedores
#===========================================================================================
version: "2.2"

services:
  gw:
    image: bin/gw
    build: 
      context: gateway
      dockerfile: Dockerfile
    container_name: gw
    networks:
      industrial-network:
        ipv4_address: 192.168.2.145
    privileged: true
    tty: true
    ports: 
      - "22:22"
      - "80:80"
      - "1883:1883"
  iot:
    image: bin/iot-device
    build: ./iot-device
    container_name: iot
    networks:
      industrial-network:
        ipv4_address: 192.168.2.196
    depends_on:
      - gw
    privileged: true
    tty: true
    volumes: 
      - ~/Documentos/volumes/iot-device/var/log/cowrie:/home/iot/cowrie/var/log/cowrie
      - ~/Documentos/volumes/iot-device/var/lib/cowrie:/home/iot/cowrie/var/lib/cowrie
      

  ics:
    image: bin/ics
    build: ./ics-part
    container_name: ics
    networks:
      - industrial-network
    depends_on:
      - gw
    privileged: true
    tty: true
    links:
      - elk
    volumes: 
      - ~/Documentos/volumes/honeyd:/home/admin/Honeyd/logs

  elk:
    image: bin/elk
    build: ./elk
    cap_add: 
      - NET_ADMIN
    privileged: true
    ports:
      - "55601:5601"
      - "59200:9200"
      - "55044:5044"
    volumes:
      - ~/Documentos/volumes/:/var/log/honeypot/

networks:
  
  industrial-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254
