filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /var/log/honeypot/honeyd/honeyd.log
  tags: ["honeyd"]

- type: log
  enabled: true
  paths:
    - /var/log/honeypot/iot-device/var/log/cowrie/cowrie.json
  tags: ["cowrie"]

  

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s


setup.template.settings:
  index.number_of_shards: 1


setup.kibana:
  host: "localhost:5601"

output.logstash:
  
  hosts: ["localhost:5044"]


processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~