# ======================== Filebeat Configuration =========================
# Ibai Castañón Osorio
# icasto01@estudiantes.unileon.es
#
# File config for filebeat
#==========================================================================

#---------------- Filebeat inputs config ------------------
filebeat.inputs:

# Config for sshd logs in gateway space
- type: log
  enabled: true
  paths:
    - /var/log/honeynet/gw_logs/auth.log
  fields:
    document_type: gateway

# Config for honeyd logs
- type: log
  enabled: true
  paths:
    - /var/log/honeynet/ics_logs/honeyd.log
  fields:
    document_type: honeyd

# Config for cowrie json logs
- input_type: log
  type: log
  enabled: true
  paths:
    - /var/log/honeynet/iot_logs/cowrie.json
  encoding: plain
  fields:
    document_type: cowrie

#---------------- Filebeat modules config ------------------
filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

#---------------- Filebeat shards config ------------------
setup.template.settings:
  index.number_of_shards: 1

#---------------- Filebeat kibana config ------------------
setup.kibana:
  host: "localhost:5601"

#---------------- Filebeat logstash config ------------------
output.logstash:
  
  hosts: ["localhost:5044"]


#---------------- Filebeat processors config ------------------
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~